services:
  - type: web
    name: controle-projetos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py createsuperuser --noinput || true
      gunicorn project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings_render
      - key: DATABASE_URL
        fromDatabase:
          name: controle-projetos-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: paulopaiva_@hotmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: babi10

databases:
  - name: controle-projetos-db
    databaseName: controle_projetos
    user: controle_projetos_user
    plan: free 