services:
  - type: web
    name: controle-projetos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings_production
      - key: DATABASE_URL
        fromDatabase:
          name: controle-projetos-db
          property: connectionString

databases:
  - name: controle-projetos-db
    databaseName: controle_projetos
    user: controle_projetos_user
    plan: free 